name: Build app and deploy to Tencent
on:
  #监听push操作
  push:
    branches:
      # mian分支，你也可以改成其他分支
      - master
jobs:
  # 任务ID
  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
    # 使用别人的action
    - uses: actions/checkout@v2
    # 步骤名称
    - name: npm nodejs
      uses: actions/setup-node@v2.5.1
      with: 
        node-version: '14.x'
    - name: npm install
      # 步骤执行指令
      run: npm install
    - name: npm run build:prod
      run: npm run build:prod
    # 命名这个任务为发布Deploy
    - name: Deploy
      # 因为构建之后，需要把代码上传到服务器上，所以需要连接到ssh，并且做一个拷贝操作
      # uses: appleboy/scp-action@v0.0.1
      # with:
      #   host: ${{ secrets.HOST }}
      #   username: ${{ secrets.USERNAME }}
      #   password: ${{ secrets.PASSWORD }}
      #   port: '22'
      #   source: 'dist/'
      #   target: '/usr/local/tomcat/apache-tomcat-8.5.82/webapps/ROOT'
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.TOKEN }}
        ARGS: '-avz --delete'
        SOURCE: 'dist/'
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: '/usr/local/tomcat/apache-tomcat-8.5.82/webapps/ROOT'